name: Build and Test Addon

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    name: setup de l'environnement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: ./addon-todo-app

  build:
    name: build de l'application
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build addon for Firefox
        run: npm run build:firefox
        working-directory: ./addon-todo-app

      - name: Zip Firefox Addon
        run: npm run zip:firefox
        working-directory: ./addon-todo-app
