name: Build and Test Addon

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    name: setup de l'environnement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci
        working-directory: ./addon-todo-app

  build:
    name: build de l'application
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: recuperer le code
        uses: actions/checkout@v3

      - name: build de l' addon pour Firefox
        run: npm run build:firefox
        working-directory: ./addon-todo-app

      - name: Zip Firefox Addon
        run: npm run zip:firefox
        working-directory: ./addon-todo-app
